# This workflow builds the Webber Go binary on every push to the main branch.
# It can be extended to create GitHub Releases or Docker images.
name: Build Webber Binary

on:
  push:
    branches:
      - main # Trigger this workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout repository code

      - name: Set up Go
        uses: actions/setup-go@v5 # Action to set up the Go environment
        with:
          go-version: '1.18.1' # Specify the Go version to use

      - name: Build Webber Binary
        run: |
          echo "Building Webber binary..."
          CGO_ENABLED=0 go build -o webber main.go
          echo "Webber binary built successfully."

      - name: Verify Binary
        run: |
          # Check if the binary was created and is executable
          ls -l webber
          ./webber -h || true # Run help command to verify it works

      - name: Upload Webber Binary as Artifact
        uses: actions/upload-artifact@v4 # Action to upload built files as workflow artifacts
        with:
          name: webber-binary # Name of the artifact
          path: webber # Path to the binary file to upload
          retention-days: 5 # How long to keep the artifact (optional)
